import Link from "next/link";
import React from "react";

const page = () => {
  return (
    <>
      <nav className="bg-gray-800 p-4">
        <div className="container mx-auto text-white text-center">
          <Link href="#" className="font-semibold text-xl tracking-tight">
            Online Remote Recruiting Ltd.
          </Link>
        </div>
      </nav>

      <div className="container mx-auto my-5 p-5 bg-white shadow-lg rounded-lg lg:w-[70%]">
        <h1 className="font-bold text-3xl mb-2">Privacy Policy</h1>
        <p className="text-gray-700 mb-4">Last updated: April 16, 2024</p>

        <h2 className="font-bold text-xl">Introduction</h2>
        <p className="text-gray-600">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the Free Privacy Policy Generator.
        </p>

        <h2 className="font-bold text-xl mt-5">
          Interpretation and Definitions
        </h2>
        <h3 className="font-semibold">Interpretation</h3>
        <p className="text-gray-600">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="font-semibold">Definitions</h3>
        <p className="text-gray-600">
          For the purposes of this Privacy Policy:
        </p>
        <ul className="list-disc pl-5 text-gray-600">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate </strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            "control" means ownership of 50% or more of the shares, equity
            interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to Online Remote Recruiting
            Ltd., 19 Thorne Street, Suite 110, Cambridge, Ontario, Canada
            N1R1S3.
          </li>
          <li>
            <strong>Cookies </strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </li>
          <li>
            <strong>Country </strong> refers to: Ontario, Canada
          </li>
          <li>
            <strong>Device </strong> means any device that can access the
            Service such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service </strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider </strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>

          <li>
            <strong>Third-party Social Media Service </strong> refers to any
            website or any social network website through which a User can log
            in or create an account to use the Service.
          </li>
          <li>
            <strong>Usage Data </strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website </strong> refers to Online Remote Recruiting Ltd.,
            accessible from https://onlineremoterecruit.com
          </li>
          <li>
            <strong>You </strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="font-bold text-xl mt-5">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="font-semibold">Types of Data Collected</h3>
        <p className="text-gray-600">
          We may ask you to provide us with certain personally identifiable
          information that can be used to contact or identify you. Examples
          include but are not limited to:
        </p>
        <ul className="list-disc pl-5 text-gray-600">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Education</li>
          <li> Previous Jobs Experience</li>
          <li>Other Information provided in Resume</li>
        </ul>

        <div>
          <h2 className="font-bold text-xl mt-5">Usage Data </h2>

          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
        </div>

        <div>
          <h2 className="font-bold text-xl mt-5">
            Information from Third-Party Social Media Services
          </h2>
          <p>
            The Company allows You to create an account and log in to use the
            Service through the following Third-party Social Media Services:
          </p>
          <ul className="list-disc pl-5 text-gray-600">
            <li>Google</li>
            <li>Facebook</li>
            <li>Instagram</li>
            <li>Twitter</li>
            <li>LinkedIn</li>
          </ul>
          <p>
            If You decide to register through or otherwise grant us access to a
            Third-Party Social Media Service, We may collect Personal data that
            is already associated with Your Third-Party Social Media Service's
            account, such as Your name, Your email address, Your activities or
            Your contact list associated with that account.
          </p>
          <p>
            You may also have the option of sharing additional information with
            the Company through Your Third-Party Social Media Service's account.
            If You choose to provide such information and Personal Data, during
            registration or otherwise, You are giving the Company permission to
            use, share, and store it in a manner consistent with this Privacy
            Policy.
          </p>
        </div>

        <div>
          <h2 className="font-bold text-xl mt-5">Contact Us</h2>
          <p className="text-gray-600">
            If you have any questions about this Privacy Policy, you can contact
            us:
          </p>
          <ul className="list-disc pl-5 text-gray-600">
            <li>
              By visiting this page on our website:{" "}
              <a
                href="https://onlineremoterecruit.com"
                className="text-blue-500 hover:text-blue-700"
              >
                https://onlineremoterecruit.com
              </a>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
};

export default page;
